config/routes.rb
Rails.application.routes.draw do
  get "login" => "sessions#new" 
  get "logout" => "sessions#destroy"
  
  resources :users 
  
  get 'home' => 'users#home'
  
  resources :sessions, only: [:new, :create, :destroy]

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	scope :notonline, -> { where.not(online: true) }

	has_secure_password

	validates_presence_of :email
	validates_uniqueness_of :email

	after_create :send_user_auth_message_to_all

	def send_user_auth_message_to_all
		UserMailer.new_user_auth_message_to_all(User.all, self)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :ensure_logged_in
  skip_filter :ensure_logged_in, only: :destroy

  helper_method :current_user # to make current user now accessible in views

  private

  def current_user
  	# unless params['_method'] == "delete"
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  	# end
	end

  def ensure_logged_in
  	if current_user.nil?
  		redirect_to login_path
  	end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_filter :ensure_logged_in
	# before_filter :path_boundary, only: [:new, :create, :destroy]

	def new
	end

	def create
		user = User.find_by_email(params[:email]).try(:authenticate, params[:password])

		if user
			session[:user_id] = user.id 
			redirect_to home_path, notice: "logged in"
		else 
			flash.now.alert = "Invalid Email or Password"
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to login_path, notice: "You logged out!"
	end

	def path_boundary
    if current_user
      redirect_to home_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_filter :ensure_logged_in, only: [:new, :create, :destroy]

	def new
		@user = User.new
	end

	def index
    @users = User.notonline
	end

	def home
    @user = current_user
  end

	def create
		@user = User.new(user_params)
		if @user.save
      UserMailer.new_auth_message(User.first, @user_auth).deliver
			redirect_to users_path, notice: "You signed up!"
		else 
			render new_user_path, notice: "You failed." 
		end
	end 

	def show
    @user = current_user
    if @user.nil?
      redirect_to login_path
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to home_path
    else
      render :edit
    end
  end

  # def detect_online
  #   @user = User.find(params[:id])
  #   if @user.update_attributes(user_params)
  #     respond_to do |format|
  #       format.js
  #       # render :update => currently update.js.erb
  #       format.html { redirect_to users_path }
  #     end
  #   else
  #     respond_to do |format|
  #       format.js { render plain: "0" }
  #       format.html { redirect_to users_path, notice: "Online detection failed." }
  #     end
  #   end
  # end

  def destroy
    if current_user.destroy!
      redirect_to logout_path
    end
  end

	private

  def set_user
    @user = current_user
  end

	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :terms)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  skip_filter :ensure_logged_in

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title UserAuthApp
    = favicon_link_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", type: "button"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
      = link_to "User Auth Login", home_path, :class => "navbar-brand"
      - unless !current_user
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "Home", home_path
          %ul.nav.navbar-nav.navbar-right
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                Settings
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Edit Account", edit_user_path(current_user)
                %li.divider
                %li= link_to "Logout", logout_path, :data => { confirm: "Logout?" }
    %br
    %br
    %br
      = yield

app/views/users/home.html.haml
.container-full
  .row
    .col-lg-12.text-center.v-center
      %br
      %br
      %h1 User Auth App
      %p.lead You are Logged In.
      %br
      %br
      %form.col-lg-12
        .input-group{style: "width:600px;text-align:center;margin:0 auto;"}
          = link_to "Log Out", logout_path, :method => "get", :data => { confirm: "Logout?" }, :class => "button btn btn-lg btn-primary"

app/views/users/new.html.haml
%script{src: "js/jquery.validate.min.js"}
%script{src: "http://code.jquery.com/jquery-1.7.min.js"}

.container-full
  .row
    .col-lg-12.text-center.v-center
      %h1 Create a New Account
      %p.lead
      %br
      %br
      .col-lg-12.center-block
        = form_for @user, url: users_path, method: :post do |f| 
          %form#register-form.form-horizontal 
            .fieldset
              .form-group
                .col-lg-6
                  .form-group{for: "name", style: "width:600px;text-align:center;margin:0 auto;"}
                    = f.label :name, :class => "col-lg-2 control-label"
                    .col-lg-10
                      = f.text_field :name, :class => "form-control"
                      %br
                  .form-group{for: "email", style: "width:600px;text-align:center;margin:0 auto;"}
                    = f.label :email, :class => "col-lg-2 control-label"
                    .col-lg-10
                      = f.email_field :email, :class => "form-control"
                      %br
                  .form-group{for: "password", style: "width:600px;text-align:center;margin:0 auto;"}
                    = f.label :password, :class => "col-lg-2 control-label"
                    .col-lg-10
                      = f.password_field :password, :class => "form-control"
                      %br
                  .form-group{for: "password_confirmation", style: "width:600px;text-align:center;margin:0 auto;"}
                    = f.label :password_confirmation, :class => "col-lg-2 control-label"
                    .col-lg-10
                      = f.password_field :password_confirmation, :class => "form-control"
                      %br
                  .actions
                    .form-group
                      .col-lg-10.col-lg-offset-2
                        = f.submit "Sign Up", :class => "btn btn-success"
                        = link_to "Cancel", new_session_path, :class => "btn btn-primary"
      #pswd_info{style: "text-align:left;"}
        %h4 Password must meet the following requirements:
        %ul
          %li#letter.invalid
            At least
            %strong one letter
          %li#capital.invalid
            At least
            %strong one capital letter
          %li#number.invalid
            At least
            %strong one number
          %li#length.invalid
            Be at least
            %strong 8 characters
      / #pswdconfirmation_info{style: "text-align:left;"}
      /   %h4 Password must meet the following requirements:
      /   %ul
      /     %li#password_confirmation.invalid
      /       Match
      /       %strong password

app/views/users/update.js.erb
1

app/views/welcome/index.html.haml
.container-full
  .row
    .col-lg-12.text-center.v-center
      %br
      %br
      %h1 User Auth App
      %p.lead Making Logging In and Out Fun! Yay!
      %br
      %br
      %form.col-lg-12
        .input-group{style: "width:600px;text-align:center;margin:0 auto;"}
          = link_to "Login", new_session_path, :class => "btn btn-block btn-primary"
          %br
          = link_to "Sign Up", new_user_path, :class => "btn btn-block btn-primary"
    / .col-lg-12.text-center.v-center 
    /   %br
    /   %br     
    /   %h3 User Auth App Users Online Now
    /   %br
    /   - @users.each do |u|
    /     %tr
    /       %td= u.name
    /       %td= check_box_tag "online", "1", u.online, data: { "user-id" => u.name }